theme: jekyll-theme-minimal

title: M. J. Michałowski
author: M. J. Michałowski

description: Epsilon

navbar-links:
  About Me: "aboutme"
  Resources:
    - LinkedIn: "https://uk.linkedin.com/in/marek-j-michalowski"

avatar: "me.jpg"
