theme: jekyll-theme-minimal

title: M. J. Michałowski
author: M. J. Michałowski

description: Penultimate Year MMath&Phys Mathematics and Physics Student at the University of Manchester marekjmichalowski@gmail.com      +44 7908878831


logo: "me.jpg"
