theme: jekyll-theme-minimal

title: M. J. Michałowski
author: M. J. Michałowski

description: Penultimate Year MMath&Phys Mathematics and Physics Student at the University of Manchester


logo: "me.jpg"
